### ISSUE TITLE
DOCKER_MODS

### ISSUE THREAD

**Issue by somedevreally** [arafatamim/linuxserver-io-mod-vuetorrent#1]
hello,

does this DOCKER_MODS works?
i added the environment to linuxserver docker-compose but doesn't work.

thanks

**Comment by arafatamim** [comment]
Did you also restart the container and then set the theme in the UI settings?

**Comment by somedevreally** [comment]
yes i restarted the container, there is no option of theme in webUI.
thanks

**Comment by arafatamim** [comment]
Goto Settings -> WEBUI and type in `/vuetorrent` then save.
[Preview](https://user-images.githubusercontent.com/31634638/128675722-7abbc91f-4b2e-4d67-a356-9693b51754e0.png)
