### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by shad-lp** [arafatamim/linuxserver-io-mod-vuetorrent#4]
Hello,

Thanks for this docker mod.
I'd like to be able to switch between the default UI and Vue.
Main reason is Vue doesn't display watched folders settings at this time.
If I erase the UI path and untick alternative UI, it stays no matter what in Vue.
I tried to restart the container too.

Anything I missed ?

**Comment by arafatamim** [comment]
That's weird, it takes effect for me as soon as I untick the option then save & reload. I'm not able to tell what's wrong on your end, sorry

**Comment by shad-lp** [comment]
Hello,

I just need to hard refresh the page (CTRL+F5) to switch the UIs instead of only F5.

**Comment by arafatamim** [comment]
Glad you figured it out!
