### ISSUE TITLE
Cannot find mod when starting a docker container

### ISSUE THREAD

**Issue by ackerthehacker2** [arafatamim/linuxserver-io-mod-vuetorrent#5]
I added the DOCKER_OPTS line to my compose file...

When I run docker compose up, I ge this:

 ✔ Container qbit  Recreated                                                            0.1s 
Attaching to qbit
qbit  | [mod-init] Attempting to run Docker Modification Logic
qbit  | [mod-init] Applying arafatamim/linuxserver-io-mod-vuetorrent files to container
**qbit  | [mod-init] arafatamim/linuxserver-io-mod-vuetorrent could not be found on registry-1.docker.io**
qbit  | [migrations] started
qbit  | [migrations] no migrations found

My docker file is:

version: '3.7'
services:
  qbit:
    image: linuxserver/qbittorrent:latest
    container_name: qbit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=8085
      - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent

**Comment by arafatamim** [comment]
I cannot reproduce locally, check your network settings
```
[+] Running 2/2
 ⠿ Network qbit_default  Created                                                                                                                  0.9s
 ⠿ Container qbit        Created                                                                                                                  3.2s
Attaching to qbit
qbit  | [mod-init] Attempting to run Docker Modification Logic
qbit  | [mod-init] Adding arafatamim/linuxserver-io-mod-vuetorrent to container
qbit  | [mod-init] Downloading arafatamim/linuxserver-io-mod-vuetorrent from registry-1.docker.io
qbit  | [mod-init] Installing arafatamim/linuxserver-io-mod-vuetorrent
qbit  | [mod-init] arafatamim/linuxserver-io-mod-vuetorrent applied to container
...
```
Alternatively, try @gabe565's [version](https://github.com/gabe565/linuxserver-mod-vuetorrent). I'll probably deprecate mine in favour of his.

**Comment by ackerthehacker2** [comment]
his mod has bigger issues in the s6 systemSent from my iPhoneOn May 30, 2023, at 10:37 PM, Tamim Arafat ***@***.***> wrote:﻿
I cannot reproduce locally, check your network settings
[+] Running 2/2
 ⠿ Network qbit_default  Created                                                                                                                  0.9s
 ⠿ Container qbit        Created                                                                                                                  3.2s
Attaching to qbit
qbit  | [mod-init] Attempting to run Docker Modification Logic
qbit  | [mod-init] Adding arafatamim/linuxserver-io-mod-vuetorrent to container
qbit  | [mod-init] Downloading arafatamim/linuxserver-io-mod-vuetorrent from registry-1.docker.io
qbit  | [mod-init] Installing arafatamim/linuxserver-io-mod-vuetorrent
qbit  | [mod-init] arafatamim/linuxserver-io-mod-vuetorrent applied to container
...

Alternatively, try @gabe565's version. I'll probably deprecate mine in favour of his.

**Comment by gabe565** [comment]
@ackerthehacker2 Hi! I just tested with this mod and mine, and both seem to install successfully. Could you run `docker compose pull` to verify you have the latest linuxserver/qbittorrent container?

Also @arafatamim thanks for linking to my mod, but I wasn't trying to replace yours! I used yours for about a year without issue. I recently have gotten into pinning app versions, so I thought it would be nice to have another strategy to install VueTorrent 🙂

**Comment by ackerthehacker2** [comment]
I went with [@gabe565](https://github.com/gabe565)'s version ...
